
production: true
proxy: edge

podSecurityContext:
  enabled: false

containerSecurityContext:
  enabled: false


ingress:
  enabled: true
postgresql:
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false

auth:
  adminUser: admin	

